[build]
publish = "public"
command = "yarn project-setup; yarn build"

[build.environment]
HUGO_VERSION = "0.115.4"
GO_VERSION = "1.20.5"

[context.production.environment]
HUGO_VERSION = "0.117.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --templateMetrics --templateMetricsHints --forceSyncStatic --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.117.0"

[context.branch-deploy]
command = "hugo --gc --minify --templateMetrics --templateMetricsHints --forceSyncStatic -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.117.0"

# Lighthouse Report Plugin
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
	package = "@netlify/plugin-lighthouse"

	# Set minimum thresholds for each report area
	[plugins.inputs.thresholds]
    performance = 0.90
    accessibility = 0.95
    best-practices = 0.75
    seo = 0.85
    # pwa = 0

  [[plugins.inputs.audits]]
    url = "$DEPLOY_PRIME_URL"

  # Audit a path other than /
  # This audit will use the top level thresholds
  [[plugins.inputs.audits]]
    url = "$DEPLOY_PRIME_URL/competitions/"

  [[plugins.inputs.audits]]
    url = "$DEPLOY_PRIME_URL/active-aircraft/"


# Sitemap Generation Plugin
# https://github.com/netlify-labs/netlify-plugin-sitemap#readme
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    # Append missing trailing slash to pretty URL
    trailingSlash = true
    changeFreq = "monthly"


# Sitemap Submission Plugin
# https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap#readme
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    # Path to the sitemap URL (optional, default = /sitemap.xml)
    sitemapPath = "/sitemap.xml"

    # Time in seconds to not submit the sitemap after successful submission
    ignorePeriod = 0

    # Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
    providers = [
      "google",
      "yandex"
    ]


# Missing Page Plugin
# https://github.com/swyxio/netlify-plugin-no-more-404#readme
[[plugins]]
package = "netlify-plugin-no-more-404"

  [plugins.inputs]
    # Either "warn" or "error"
    on404 = "error"

    # Change this key to a new one any time you need to restart from scratch
    cacheKey = "MyCacheKey"

    # (For development) turn true for extra diagnostic logging
    debugMode = false


# Accessibility Check Plugin
# https://github.com/netlify-labs/netlify-plugin-a11y#readme
[[plugins]]
  package = "@netlify/plugin-a11y"

  [plugins.inputs]
    # Indicates which pages of your site to check
    checkPaths = ['/']

    # Whether to fail the build if a11y issues are found
    failWithIssues = true

    # Directories that should not be checked for a11y issues
    ignoreDirectories = ["1"]

    # Indicates elements that should be ignored by a11y testing
    ignoreElements = '.search-modal, #nav-menu > li, html > body > main > section:nth-child(2) > div > ul > li'

    # Indicates guidelines and types to ignore (pa11y docs)
    ignoreGuidelines = []

    # The WCAG standard level against which pages are checked
    # wcagLevel =


# Links Check Plugin
# https://github.com/Munter/netlify-plugin-checklinks#readme
# [[plugins]]
# package = "netlify-plugin-checklinks"

#   [plugins.inputs]
#     # An array of glob patterns for pages on your site
#     # Recursive traversal will start from these
#     entryPoints = [
#       "*.html",
#     ]

#     # Recurse through all the links and asset references on your page, starting
#     # at the entrypoints
#     recursive = true

#     # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
#     # by default. Enabling pretty mode makes the output easier on the eyes.
#     pretty = true

#     # You can mark some check as skipped, which will block checklinks
#     # from ever attempting to execute them.
#     # skipPatterns is an array of strings you can match against failing reports
#     skipPatterns = []

#     # You can mark some check as todo, which will execute the check, but allow failures.
#     # todoPatterns is an array of strings you can match against failing reports
#     todoPatterns = []

#     # Report on all broken links to external pages.
#     # Enabling this will make your tests more brittle, since you can't control
#     # external pages.
#     checkExternal = true

#     # Enable to check references to source maps, source map sources etc.
#     # Many build tools don't emit working references, so this is disabled by default
#     followSourceMaps = false
